# Generated by Django 3.2.2 on 2021-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='client_id',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
